name: flutter_native_log_handler
description: Listen to native Android and iOS logs (basically listen to stdout/stderr).
version: 0.1.2
homepage: https://github.com/Goddchen/flutter_native_logs
repository: https://github.com/Goddchen/flutter_native_logs

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.1.1

flutter:
  plugin:
    platforms:
      android:
        package: de.goddchen.flutter.flutter_native_logs
        pluginClass: FlutterNativeLogsPlugin
      ios:
        pluginClass: FlutterNativeLogsPlugin
