name: flutter_native_log_handler
description: Listen to native Android and iOS logs (basically listen to stdout/stderr).
version: 1.1.1
homepage: https://github.com/Goddchen/flutter_native_logs
repository: https://github.com/Goddchen/flutter_native_logs

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0 <4.0.0"

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.6

flutter:
  plugin:
    platforms:
      android:
        package: de.goddchen.flutter.flutter_native_logs
        pluginClass: FlutterNativeLogsPlugin
      ios:
        pluginClass: FlutterNativeLogsPlugin
