name: flutter_native_logs
description: Deal with native Android and iOS logs.
version: 1.0.0
homepage: https://github.com/Goddchen/flutter_native_logs

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: de.goddchen.flutter.flutter_native_logs
        pluginClass: FlutterNativeLogsPlugin
      ios:
        pluginClass: FlutterNativeLogsPlugin
