name: main workflow
on:
  push:
    branches:
      - main
jobs:
  flutter_analyze:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.3"
      - working-directory: flutter_native_log_handler/example/
        run: flutter pub get
      - working-directory: flutter_native_log_handler/
        run: flutter analyze --fatal-infos --fatal-warnings
  flutter_format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.3"
      - working-directory: flutter_native_log_handler/
        run: flutter format --output none --set-exit-if-changed .\example\ .\lib\ .\test\
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.3"
      - working-directory: flutter_native_log_handler/
        run: flutter test
