name: main workflow
on:
  push:
    branches:
      - main
jobs:
  flutter_analyze:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: kuhnroyal/flutter-fvm-config-action/setup@v3
        with:
          path: flutter_native_log_handler/
      - working-directory: flutter_native_log_handler/example/
        run: flutter pub get
      - working-directory: flutter_native_log_handler/
        run: flutter analyze --fatal-infos --fatal-warnings
  flutter_format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: kuhnroyal/flutter-fvm-config-action/setup@v3
        with:
          path: flutter_native_log_handler/
      - working-directory: flutter_native_log_handler/
        run: dart format --output none --set-exit-if-changed .\example\ .\lib\ .\test\
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: kuhnroyal/flutter-fvm-config-action/setup@v3
        with:
          path: flutter_native_log_handler/
      - working-directory: flutter_native_log_handler/
        run: flutter test
